-- Vail Phase 11 first-party site analytics
-- Private, service-role-only page-view storage and owner reporting.

CREATE TABLE IF NOT EXISTS public.site_page_views (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    visitor_id UUID NOT NULL,
    session_id UUID NOT NULL,
    path TEXT NOT NULL,
    referrer_url TEXT,
    referrer_host TEXT,
    source TEXT NOT NULL DEFAULT 'Direct',
    medium TEXT,
    campaign TEXT,
    country_code TEXT,
    region TEXT,
    city TEXT,
    device_type TEXT NOT NULL DEFAULT 'Desktop',
    browser TEXT,
    operating_system TEXT,
    ip_hash TEXT,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT site_page_views_path_length CHECK (char_length(path) BETWEEN 1 AND 500),
    CONSTRAINT site_page_views_country_code_length CHECK (country_code IS NULL OR char_length(country_code) = 2)
);

CREATE INDEX IF NOT EXISTS idx_site_page_views_occurred_at
ON public.site_page_views(occurred_at DESC);

CREATE INDEX IF NOT EXISTS idx_site_page_views_visitor_occurred_at
ON public.site_page_views(visitor_id, occurred_at DESC);

CREATE INDEX IF NOT EXISTS idx_site_page_views_session_occurred_at
ON public.site_page_views(session_id, occurred_at DESC);

CREATE INDEX IF NOT EXISTS idx_site_page_views_source_occurred_at
ON public.site_page_views(source, occurred_at DESC);

CREATE INDEX IF NOT EXISTS idx_site_page_views_country_occurred_at
ON public.site_page_views(country_code, occurred_at DESC);

ALTER TABLE public.site_page_views ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.get_site_analytics(p_days INTEGER DEFAULT 30)
RETURNS JSONB
LANGUAGE SQL
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
WITH params AS (
    SELECT GREATEST(1, LEAST(COALESCE(p_days, 30), 365)) AS days
),
bounds AS (
    SELECT
        NOW() - make_interval(days => days) AS current_start,
        NOW() - make_interval(days => days * 2) AS previous_start
    FROM params
),
current_views AS (
    SELECT views.*
    FROM public.site_page_views AS views, bounds
    WHERE views.occurred_at >= bounds.current_start
),
previous_views AS (
    SELECT views.*
    FROM public.site_page_views AS views, bounds
    WHERE views.occurred_at >= bounds.previous_start
      AND views.occurred_at < bounds.current_start
),
current_sessions AS (
    SELECT session_id, COUNT(*)::INTEGER AS view_count
    FROM current_views
    GROUP BY session_id
),
current_summary AS (
    SELECT
        COUNT(*)::INTEGER AS views,
        COUNT(DISTINCT visitor_id)::INTEGER AS visitors,
        COUNT(DISTINCT session_id)::INTEGER AS sessions
    FROM current_views
),
previous_summary AS (
    SELECT
        COUNT(*)::INTEGER AS views,
        COUNT(DISTINCT visitor_id)::INTEGER AS visitors,
        COUNT(DISTINCT session_id)::INTEGER AS sessions
    FROM previous_views
),
all_time_summary AS (
    SELECT
        COUNT(*)::INTEGER AS views,
        COUNT(DISTINCT visitor_id)::INTEGER AS visitors
    FROM public.site_page_views
),
today_summary AS (
    SELECT
        COUNT(*)::INTEGER AS views,
        COUNT(DISTINCT visitor_id)::INTEGER AS visitors
    FROM public.site_page_views
    WHERE occurred_at >= date_trunc('day', NOW())
),
daily AS (
    SELECT
        series.day::DATE AS day,
        COUNT(current_views.id)::INTEGER AS views,
        COUNT(DISTINCT current_views.visitor_id)::INTEGER AS visitors
    FROM bounds
    CROSS JOIN LATERAL generate_series(
        date_trunc('day', bounds.current_start),
        date_trunc('day', NOW()),
        INTERVAL '1 day'
    ) AS series(day)
    LEFT JOIN current_views
      ON (current_views.occurred_at AT TIME ZONE 'UTC')::DATE = series.day::DATE
    GROUP BY series.day
    ORDER BY series.day
),
sources AS (
    SELECT
        source,
        COUNT(*)::INTEGER AS views,
        COUNT(DISTINCT visitor_id)::INTEGER AS visitors
    FROM current_views
    GROUP BY source
    ORDER BY views DESC, source
    LIMIT 10
),
locations AS (
    SELECT
        COALESCE(NULLIF(country_code, ''), 'XX') AS country_code,
        COALESCE(NULLIF(region, ''), 'Unknown region') AS region,
        COALESCE(NULLIF(city, ''), 'Unknown city') AS city,
        COUNT(*)::INTEGER AS views,
        COUNT(DISTINCT visitor_id)::INTEGER AS visitors
    FROM current_views
    GROUP BY country_code, region, city
    ORDER BY visitors DESC, views DESC
    LIMIT 12
),
pages AS (
    SELECT
        path,
        COUNT(*)::INTEGER AS views,
        COUNT(DISTINCT visitor_id)::INTEGER AS visitors
    FROM current_views
    GROUP BY path
    ORDER BY views DESC, path
    LIMIT 10
),
devices AS (
    SELECT
        device_type,
        COUNT(*)::INTEGER AS views,
        COUNT(DISTINCT visitor_id)::INTEGER AS visitors
    FROM current_views
    GROUP BY device_type
    ORDER BY views DESC, device_type
),
recent AS (
    SELECT
        occurred_at,
        path,
        source,
        country_code,
        region,
        city,
        device_type,
        browser
    FROM current_views
    ORDER BY occurred_at DESC
    LIMIT 20
)
SELECT jsonb_build_object(
    'generatedAt', NOW(),
    'rangeStart', (SELECT current_start FROM bounds),
    'summary', jsonb_build_object(
        'views', current_summary.views,
        'visitors', current_summary.visitors,
        'sessions', current_summary.sessions,
        'viewsPerSession', CASE
            WHEN current_summary.sessions = 0 THEN 0
            ELSE ROUND(current_summary.views::NUMERIC / current_summary.sessions, 2)
        END,
        'bounceRate', COALESCE(
            ROUND(
                100.0 * (SELECT COUNT(*) FROM current_sessions WHERE view_count = 1)
                / NULLIF((SELECT COUNT(*) FROM current_sessions), 0),
                1
            ),
            0
        ),
        'previousViews', previous_summary.views,
        'previousVisitors', previous_summary.visitors,
        'previousSessions', previous_summary.sessions,
        'allTimeViews', all_time_summary.views,
        'allTimeVisitors', all_time_summary.visitors,
        'todayViews', today_summary.views,
        'todayVisitors', today_summary.visitors
    ),
    'daily', COALESCE((SELECT jsonb_agg(to_jsonb(daily) ORDER BY day) FROM daily), '[]'::JSONB),
    'sources', COALESCE((SELECT jsonb_agg(to_jsonb(sources) ORDER BY views DESC) FROM sources), '[]'::JSONB),
    'locations', COALESCE((SELECT jsonb_agg(to_jsonb(locations) ORDER BY visitors DESC, views DESC) FROM locations), '[]'::JSONB),
    'pages', COALESCE((SELECT jsonb_agg(to_jsonb(pages) ORDER BY views DESC) FROM pages), '[]'::JSONB),
    'devices', COALESCE((SELECT jsonb_agg(to_jsonb(devices) ORDER BY views DESC) FROM devices), '[]'::JSONB),
    'recent', COALESCE((SELECT jsonb_agg(to_jsonb(recent) ORDER BY occurred_at DESC) FROM recent), '[]'::JSONB)
)
FROM current_summary
CROSS JOIN previous_summary
CROSS JOIN all_time_summary
CROSS JOIN today_summary;
$$;

REVOKE ALL ON TABLE public.site_page_views FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.get_site_analytics(INTEGER) FROM PUBLIC, anon, authenticated;
GRANT ALL ON TABLE public.site_page_views TO service_role;
GRANT EXECUTE ON FUNCTION public.get_site_analytics(INTEGER) TO service_role;
