import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import ts from 'typescript';
import {test} from 'node:test';
function loader(overrides={}){const cache={};return function load(file){file=path.resolve(file);if(cache[file])return cache[file];const exports={};cache[file]=exports;const code=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;vm.runInNewContext(code,{exports,Date,URL,Set,Map,AbortSignal,process:{env:{OPENAI_API_KEY:'test'}},fetch:overrides.fetch,require(n){if(n in overrides)return overrides[n];if(n==='server-only')return {};if(n.startsWith('.')){const p=path.resolve(path.dirname(file),n);if(n.endsWith('.json'))return {default:JSON.parse(fs.readFileSync(p,'utf8'))};return load(p+'.ts');}throw Error('Unexpected import '+n);}});return exports;};}
const load=loader();const {DEFAULT_SCREEN,validateScreen,evaluateScreen,screenDates}=load('src/lib/research-screen.ts');
const trade=(id,member='K000389',extra={})=>({id,doc_id:id,member_id:member,politician_name:member,ticker:'NVDA',asset_type:'ST',amount_range:'$1,001 - $15,000',asset_name:'NVIDIA',transaction_type:'buy',transaction_date:'2026-08-01',published_date:'2026-09-01',source_url:'https://example.com/source',...extra});
const classification=[{ticker:'NVDA',company_name:'NVIDIA',industry:'Semiconductors & Related Devices',source_url:'https://data.sec.gov/',verified_at:'2026-09-01'}];
test('four trades from one person do not satisfy three distinct buyers',()=>{const r=evaluateScreen([1,2,3,4].map(i=>trade(String(i))),DEFAULT_SCREEN,classification,null,null);assert.equal(r.stocks.length,0);});
test('duplicate source rows count once, independent purchasers qualify',()=>{const rows=[trade('1'),trade('1'),trade('2','P000197'),trade('3','T000278')];const r=evaluateScreen(rows,DEFAULT_SCREEN,classification,null,null);assert.equal(r.stocks[0].politicians,3);assert.equal(r.stocks[0].trades.length,3);});
test('industry excludes unclassified tickers and reports missing coverage',()=>{const f={...DEFAULT_SCREEN,minPoliticians:1,industry:classification[0].industry};const r=evaluateScreen([trade('1'),trade('2','P000197',{ticker:'ZZZ'})],f,classification,null,null);assert.equal(r.stocks.length,1);assert.equal(r.coverage.unclassifiedTickers,1);});
test('committee and politician filters intersect instead of broadening the search',()=>{const rows=[trade('1'),trade('2','P000197')];const r=evaluateScreen(rows,{...DEFAULT_SCREEN,minPoliticians:1,memberId:'P000197'},classification,new Set(['K000389']),null);assert.equal(r.stocks.length,0);});
test('sales cannot qualify a purchase-only screen',()=>{const r=evaluateScreen([trade('1','P000197',{transaction_type:'sell'})],{...DEFAULT_SCREEN,minPoliticians:1},classification,null,null);assert.equal(r.stocks.length,0);});
test('unsupported filters, invalid dates, and SQL-like ticker strings are rejected',()=>{for(const patch of [{days:0},{days:367},{minPoliticians:0},{ticker:"NVDA');drop table companies;--"},{profit:1},{industry:''},{days:'30'}])assert.throws(()=>validateScreen({...DEFAULT_SCREEN,...patch}));});
test('rolling windows include exactly the requested days across month and leap boundaries',()=>{assert.equal(screenDates(30,new Date('2026-09-16T12:00Z')).start,'2026-08-18');assert.equal(screenDates(1,new Date('2024-02-29T12:00Z')).start,'2024-02-29');});
const next={'NextResponse':{json:(body,options={})=>({body,status:options.status||200})}};
class ApiRouteError extends Error{constructor(status,code,message){super(message);this.status=status;this.code=code;}}
test('anonymous users cannot invoke the paid model',async()=>{let invoked=false;const route=loader({'next/server':next,'@/lib/research-screen-server':{researchData:async()=>({catalog:{}}),runScreen:async()=>({})},'@/lib/research-model':{interpretScreen:async()=>{invoked=true;}},'@/lib/auth-server':{requireApiUser:async()=>{throw new ApiRouteError(401,'AUTH','Sign in');},ApiRouteError},'@/lib/supabase-admin':{getAdminSupabase:()=>{throw Error('Must not query');}}})('src/app/api/research/route.ts');const r=await route.POST({text:async()=>JSON.stringify({action:'interpret',question:'three buyers'})});assert.equal(r.status,401);assert.equal(invoked,false);});
test('exhausted durable quota blocks model calls',async()=>{let invoked=false;const route=loader({'next/server':next,'@/lib/research-screen-server':{researchData:async()=>({catalog:{}}),runScreen:async()=>({})},'@/lib/research-model':{interpretScreen:async()=>{invoked=true;}},'@/lib/auth-server':{requireApiUser:async()=>({id:'me'}),ApiRouteError},'@/lib/supabase-admin':{getAdminSupabase:()=>({rpc:async()=>({data:false,error:null})})}})('src/app/api/research/route.ts');const r=await route.POST({text:async()=>JSON.stringify({action:'interpret',question:'three buyers'})});assert.equal(r.status,429);assert.equal(invoked,false);});
test('saved screen deletion is scoped to the authenticated user',async()=>{const calls=[];const q={delete(){return q;},eq(...args){calls.push(args);return q;},then(resolve){return Promise.resolve({error:null}).then(resolve);}};const route=loader({'next/server':next,'@/lib/auth-server':{requireApiUser:async()=>({id:'authenticated-user'}),ApiRouteError},'@/lib/account-route':{accountRouteErrorResponse:e=>({status:e.status})},'@/lib/supabase-admin':{getAdminSupabase:()=>({from:()=>q})},'@/lib/research-screen':{validateScreen}})('src/app/api/account/research-screens/route.ts');const r=await route.DELETE({url:'https://example.com?id=00000000-0000-0000-0000-000000000001&user_id=someone-else'});assert.equal(r.status,200);assert.deepEqual(calls[1],['user_id','authenticated-user']);});
