import Link from 'next/link';
import { CompanyLogo } from '@/components/identity-images';
export const metadata = { title: 'The stocks behind the AI buildout — Sunday Brief' };
const stories = [
 {ticker:'AVGO',name:'Broadcom',count:'4 buyers · 1 seller',title:'The chip story extends beyond NVIDIA.',text:'Broadcom led the available 30-day disclosure window by distinct buyers. Purchases were attributed to David Taylor, Ro Khanna, John Boozman and Rick Allen. That makes it the most widely bought name in this snapshot—not necessarily the largest investment by dollars.',context:'Broadcom’s September 2 earnings release reported $16.7 billion in AI semiconductor revenue, up 221% year over year. Its business results give readers a concrete reason to examine the company alongside the better-known AI chip names.',note:'These purchases were not all recent: the recorded transaction dates range from April 2025 to August 2026. They should not be read as a coordinated response to September earnings.',source:'https://investors.broadcom.com/news-releases/news-release-details/broadcom-inc-announces-third-quarter-fiscal-year-2026-financial'},
 {ticker:'MSFT',name:'Microsoft',count:'3 buyers · 2 sellers',title:'Cloud demand, with activity on both sides.',text:'Microsoft appeared in purchase disclosures from Gilbert Cisneros, Ro Khanna and John Boozman during the same 30-day window. Two politicians also reported sales. The distinction matters: attention to a stock is not the same thing as agreement about it.',context:'Microsoft’s July 29 earnings announcement centered on cloud and AI growth. This puts the company on the software and cloud side of the same investment story that Broadcom represents in semiconductors.',note:'Cisneros’s August 18 purchase appeared in a September 10 filing, within this week’s window. Other purchases in the monthly count were older, including April 2025 transactions.',source:'https://news.microsoft.com/source/2026/07/29/microsoft-cloud-and-ai-strength-fuels-fourth-quarter-results-4/'},
 {ticker:'PWR',name:'Quanta Services',count:'2 buyers · 0 sellers',title:'Behind the chips: the electricity.',text:'Quanta purchases were attributed to Gilbert Cisneros and Ro Khanna in the monthly snapshot, with no eligible sales recorded in that window. Cisneros’s August 27 transaction was disclosed September 10; Khanna’s August 10 transaction was disclosed September 4.',context:'Quanta’s second-quarter report connects utility demand with electricity needs from data centers, manufacturing and electrification. It offers a different angle on the technology buildout: the infrastructure needed to power it.',note:'This is an editorial connection between company activity and the disclosure data. The filings do not establish that either buyer was investing because of AI.',source:'https://www.sec.gov/Archives/edgar/data/1050915/000105091526000025/pwr-20260630.htm'},
];
export default function Edition(){return <main id="main" className="container brief-page">
 <header className="brief-heading"><Link className="eyebrow" href="/sunday-brief">SUNDAY BRIEF · VAIL</Link><p className="brief-meta">SEPTEMBER 13, 2026 · DRAFT FOR REVIEW · 3 MIN READ</p><h1>The stocks behind<br/><em>the AI buildout.</em></h1><p>Chips, cloud, and the power grid.<br/>Three names worth a closer look.</p></header>
 <div className="brief-edition"><span>THIS WEEK: SEPTEMBER 7–13</span><span>64 purchases · 97 sales*</span></div>
 <article className="brief-introduction"><p>The interesting story isn’t just who traded. It’s which businesses appear in the disclosures, and how those businesses connect to the world outside Washington.</p><p>This week’s available records showed no stock with more than one distinct buyer. To give that quiet week context, we looked back over <strong>August 15–September 13</strong>. Broadcom and Microsoft led by buyer count; Quanta adds an infrastructure angle to the wider AI story.</p>
 <aside className="brief-window">All buyer and seller counts below cover <strong>30 days of newly disclosed activity</strong>. They do not mean the trades happened in the last 30 days.</aside>
 {stories.map((s,i)=><section className="brief-stock-story" key={s.ticker}><div className="brief-stock-heading"><CompanyLogo ticker={s.ticker}/><div><strong>{s.name} <span className="muted">{s.ticker}</span></strong><small>{s.count} · 30-day disclosures</small></div><span className="muted">0{i+1}</span></div><h2>{s.title}</h2><p>{s.text}</p><p>{s.context} <a href={s.source} target="_blank" rel="noopener noreferrer">Company source ↗</a></p><p className="brief-story-note">{s.note}</p><Link className="text-link" href={`/ticker/${s.ticker}`}>Explore {s.ticker} disclosures →</Link></section>)}
 <h2>One theme. Different businesses.</h2><p>Our reading: these names provide three ways to explore the AI buildout—semiconductors, cloud services and electricity infrastructure. That is a research starting point, not evidence of a shared congressional strategy or a prediction of returns.</p>
 <p className="brief-footnote">*Weekly counts: eligible stock and ETF transactions in Vail’s September 7–13 snapshot; latest included filing September 11. Includes household activity. Available coverage is incomplete. Monthly counts are distinct politicians, not transaction counts. Draft figures require final source review before distribution.</p>
 <Link className="button secondary" href="/analysis">Explore the full analysis →</Link></article>
 </main>}
