"use client";
import { useEffect, useState } from 'react';
type Candidate = {id:string;title:string;draft_text:string;rationale:string|null;status:string;created_at:string;payload:Record<string,unknown>|null};
export function HqMarketing({token,password}:{token:string;password:string}) {
 const [rows,setRows]=useState<Candidate[]>([]),[selected,setSelected]=useState(''),[draft,setDraft]=useState(''),[filter,setFilter]=useState('pending_review'),[error,setError]=useState(''),[notice,setNotice]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[configured,setConfigured]=useState(false),[revision,setRevision]=useState(0);
 useEffect(()=>{const controller=new AbortController();fetch('/api/hq/marketing',{headers:{Authorization:`Bearer ${token}`,'x-hq-password':password},cache:'no-store',signal:controller.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);return d;}).then(d=>{setRows(d.candidates);setConfigured(d.configured);setError('');}).catch(e=>{if(!controller.signal.aborted)setError(e.message);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[token,password,revision]);
 const visible=rows.filter(r=>r.status===filter),active=visible.find(r=>r.id===selected);
 async function save(action:'save'|'dismiss') {if(!active)return;setSaving(true);setError('');setNotice('');try{const r=await fetch('/api/hq/marketing',{method:'PATCH',headers:{Authorization:`Bearer ${token}`,'x-hq-password':password,'Content-Type':'application/json'},body:JSON.stringify({id:active.id,draft,action})});const d=await r.json();if(!r.ok)throw Error(d.error);setRows(rows.map(row=>row.id===active.id?{...row,draft_text:draft,status:action==='dismiss'?'rejected':row.status}:row));setNotice(action==='dismiss'?'Candidate dismissed.':'Draft saved.');}catch(e){setError(e instanceof Error?e.message:'Could not save.');}finally{setSaving(false);}}
 return <section className="hq-section"><span className="eyebrow">MARKETING / TWITTER</span><h2>Your next post.</h2><p className="muted">Review the story, refine the wording, and check the disclosure.</p><div className="hq-grid"><div className="hq-stat"><span>X integration</span><b>{configured?'Credentials configured':'Credentials not configured'}</b><small>{configured?'API permissions and connectivity still need verification.':'Add the existing X credentials to this environment.'}</small></div><div className="hq-stat"><span>Publishing</span><b>Review workspace</b><small>Saving a draft does not approve or publish it.</small></div><div className="hq-stat"><span>News monitoring</span><b>Not connected</b><small>Account monitoring and image attachments come next.</small></div></div>
 <div className="ranking-controls"><label>Queue <select value={filter} disabled={saving} onChange={e=>{setFilter(e.target.value);setSelected('');setNotice('');}}><option value="pending_review">Needs review</option><option value="approved">Approved</option><option value="posted">Posted</option><option value="rejected">Dismissed</option></select></label><button className="button secondary" disabled={saving} onClick={()=>setRevision(n=>n+1)}>Refresh queue</button></div>
 <p className="fine-print">Politicians only · $25,000 minimum disclosed value, combined for groups; also includes 2+ politicians buying within a cluster window of 14 days or less. Filtered from the latest 100 saved Twitter candidates. Older items need a freshness check before use. The existing compiler supplies this queue.</p>{error&&<p role="alert" className="error">{error}</p>}{notice&&<p role="status">{notice}</p>}
 {loading?<p role="status">Loading candidates…</p>:<div className="hq-marketing-layout"><div className="hq-candidates">{!visible.length?<p>No candidates in this view yet.</p>:visible.map(row=><button disabled={saving} className={`hq-candidate ${selected===row.id?'selected':''}`} key={row.id} onClick={()=>{setSelected(row.id);setDraft(row.draft_text);setNotice('');}}><strong>{row.title}</strong><small>{new Date(row.created_at).toLocaleDateString()} · {row.status.replaceAll('_',' ')}</small></button>)}</div><div className="hq-stat">{active?<><span className="eyebrow">POST PREVIEW & EDITOR</span><label htmlFor="tweet-draft">Tweet text</label><textarea id="tweet-draft" rows={10} value={draft} disabled={saving||active.status!=='pending_review'} onChange={e=>setDraft(e.target.value)} /><small>Check X’s weighted character limit before publishing.</small><h3>Why this candidate</h3><p>{active.rationale||'No rationale saved. Review the source before using this draft.'}</p><details><summary>Supporting data</summary><pre className="hq-evidence">{JSON.stringify(active.payload,null,2)}</pre></details>{active.status==='pending_review'&&<div className="ranking-controls"><button className="button primary" disabled={saving||!draft.trim()} onClick={()=>save('save')}>{saving?'Saving…':'Save draft'}</button><button className="button secondary" disabled={saving} onClick={()=>save('dismiss')}>Dismiss</button></div>}</>:<><h3>Choose a candidate</h3><p>Select a story to review its wording and supporting data.</p></>}</div></div>}</section>;
}
